name: slack weather action

on: [push]
#on:
#    schedule:
#        - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 소스코드를 ubuntu에 복사
      uses: actions/checkout@v2
    - name: ubuntu에 python 개발환경 구축
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: python 모듈 설치
      run: pip install -r req.txt
    - name: python main.py 실행
      env:
        slack_token: ${{ secrets.SLACK_TOKEN }}
      run: python main.py
